% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Chapter 1: Homework},
  pdfauthor={711378912 蔡宜諠},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Chapter 1: Homework}
\author{711378912 蔡宜諠}
\date{03/06/2025}

\begin{document}
\maketitle

設計一個類似的問題，計算 Wald test 及 Score test
所造成的信賴區間，並執行二個檢定（大樣本及小樣本），報告其結果

\hypertarget{ux4f5cux696dux8209ux4f8bux7bc4ux4f8bux5de5ux7a0bux5e2bux5b78ux6b77ux78a9ux58ebux542bux4ee5ux4e0aux6bd4ux4f8b}{%
\section{作業舉例範例：工程師學歷碩士(含)以上比例}\label{ux4f5cux696dux8209ux4f8bux7bc4ux4f8bux5de5ux7a0bux5e2bux5b78ux6b77ux78a9ux58ebux542bux4ee5ux4e0aux6bd4ux4f8b}}

\hypertarget{ux4e8bux5be6}{%
\subsection{事實}\label{ux4e8bux5be6}}

根據產業統計，過去科技業的工程師擁有碩士學歷的比例約為 50\%。

\begin{longtable}[]{@{}lrrr@{}}
\toprule\noalign{}
血型 & 學士(含)以下 & 碩士(含)以上 & Total \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
百分比 & 50 & 50 & 100 \\
\end{longtable}

\hypertarget{ux731cux60f3}{%
\subsection{猜想}\label{ux731cux60f3}}

\begin{itemize}
\item
  隨著科技業對高階技術人才需求增加，近年來碩士學歷可能更受重視。
\item
  如果選擇某科技公司內的工程師來調查，他們擁有碩士學歷的比例可能高於50\%。
\item
  利用統計檢定來檢驗這個猜想

  \begin{itemize}
  \tightlist
  \item
    \(H_0: \pi_0=0.50\)
  \item
    \(H_a: \pi_0>0.50\)
  \end{itemize}
\end{itemize}

\hypertarget{ux5be6ux9a57}{%
\subsection{實驗}\label{ux5be6ux9a57}}

\begin{itemize}
\tightlist
\item
  調查併記錄公司工程師學歷比例
\end{itemize}

\hypertarget{ux89c0ux5bdfux7d50ux679c}{%
\subsection{觀察結果：}\label{ux89c0ux5bdfux7d50ux679c}}

\begin{itemize}
\tightlist
\item
  參與調查人數為 \(n\)
\item
  擁有碩士學歷的人數為 \(x\)
\item
  碩士比例為 \(x/n\)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{40}\NormalTok{; x }\OtherTok{\textless{}{-}} \DecValTok{26} \CommentTok{\# 工程師總人數40人，26人為碩士(含)學歷以上}
\NormalTok{alpha }\OtherTok{\textless{}{-}} \FloatTok{0.05}
\NormalTok{pihat }\OtherTok{\textless{}{-}}\NormalTok{ x}\SpecialCharTok{/}\NormalTok{n; pi0 }\OtherTok{\textless{}{-}} \FloatTok{0.44}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux5340ux9593ux4f30ux8a08-confidence-interval}{%
\subsection{區間估計 (Confidence
Interval)}\label{ux5340ux9593ux4f30ux8a08-confidence-interval}}

\begin{itemize}
\tightlist
\item
  Wald Test
\end{itemize}

\[\hat{\pi}\pm
z_{\alpha/2}\sqrt{\frac{\hat{\pi}(1-\hat{\pi})}{n}}.\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lb }\OtherTok{\textless{}{-}}\NormalTok{ pihat }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(pihat}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{pihat)}\SpecialCharTok{/}\NormalTok{n) }
\NormalTok{ub }\OtherTok{\textless{}{-}}\NormalTok{ pihat }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(pihat}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{pihat)}\SpecialCharTok{/}\NormalTok{n) }
\FunctionTok{cat}\NormalTok{(}\StringTok{"Wald 95\% CI is ["}\NormalTok{, lb, ub, }\StringTok{"]}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Wald 95% CI is [ 0.5021883 0.7978117 ]
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Score Test
\end{itemize}

\[
  \hat{\pi}\left(\frac{n}{n+z_{\alpha/2}^2}\right)+
  \frac{1}{2}\left(\frac{z_{\alpha/2}^2}{n+z_{\alpha/2}^2}\right)
  \pm\sqrt{\frac{1}{n+z_{\alpha/2}^2}\left[\left(\frac{n\hat{\pi}(1-\hat{\pi})}{n+z_{\alpha/2}^2}\right)+
  \left(\frac{z_{\alpha/2}^2}{4(n+z_{\alpha/2}^2)}\right)\right]}
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z2 }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{qnorm}\NormalTok{(alpha}\SpecialCharTok{/}\DecValTok{2}\NormalTok{))}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{mu }\OtherTok{\textless{}{-}}\NormalTok{ pihat}\SpecialCharTok{*}\NormalTok{n}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{z2) }\SpecialCharTok{+}\NormalTok{ .}\DecValTok{5}\SpecialCharTok{*}\NormalTok{(z2}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{z2))}
\NormalTok{sig }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((n}\SpecialCharTok{*}\NormalTok{pihat}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{pihat)}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{z2) }\SpecialCharTok{+}\NormalTok{ z2}\SpecialCharTok{/}\DecValTok{4}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{z2))}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{z2))}
\NormalTok{lb }\OtherTok{\textless{}{-}}\NormalTok{ mu }\SpecialCharTok{{-}}\NormalTok{ sig}
\NormalTok{ub }\OtherTok{\textless{}{-}}\NormalTok{ mu }\SpecialCharTok{+}\NormalTok{ sig}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Score 95\% CI is ["}\NormalTok{, lb, ub, }\StringTok{"]}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Score 95% CI is [ 0.5645095 0.709204 ]
\end{verbatim}

\hypertarget{ux5047ux8a2dux6aa2ux5b9a}{%
\subsection{假設檢定}\label{ux5047ux8a2dux6aa2ux5b9a}}

\hypertarget{large-sample-approximation}{%
\subsubsection{Large sample
approximation}\label{large-sample-approximation}}

\begin{itemize}
\item
  Check \(np \geq 5\) and \(n(1-p) \geq 5\)
\item
  \(H_0\) vs \(H_a\)
\item
  \(\alpha=0.05\)
\item
  Test statistics

  \begin{itemize}
  \tightlist
  \item
    Wald Test \[
      \frac{\hat{\pi} - \pi_0}{\sqrt{\hat{\pi} (1-\hat{\pi})/n}} = t_w
    \]
  \item
    Score Test \[
      \frac{\hat{\pi} - \pi_0}{\sqrt{\pi_0 (1-\pi_0)/n}} = t_s
    \]
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(pihat}\SpecialCharTok{{-}}\NormalTok{pi0)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(pihat}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{pihat)}\SpecialCharTok{/}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.784573
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(pihat}\SpecialCharTok{{-}}\NormalTok{pi0)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(pi0}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{pi0)}\SpecialCharTok{/}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.675648
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Critical value \(1.645\) (one-tailed)
\item
  Decision:

  \begin{itemize}
  \tightlist
  \item
    Walt Test: reject \(H_0\) if \(t_w > 1.645\)
  \item
    Score Test: regject \(H_0\) if \(t_s > 1.645\)
  \end{itemize}
\end{itemize}

\hypertarget{small-sample-exact-test}{%
\subsubsection{Small Sample Exact Test}\label{small-sample-exact-test}}

\begin{itemize}
\tightlist
\item
  \(p\)-value is
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pbinom}\NormalTok{(x}\DecValTok{{-}1}\NormalTok{, n, pi0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.006029371
\end{verbatim}

\begin{itemize}
\tightlist
\item
  mid \(p\)-value
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pbinom}\NormalTok{(x, n, pi0) }\SpecialCharTok{+} \FunctionTok{dbinom}\NormalTok{(x, n, pi0)}\SpecialCharTok{/}\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.004171611
\end{verbatim}

\hypertarget{summary}{%
\section{📊 Summary}\label{summary}}

根據本研究的統計檢定結果，我們對某科技公司內工程師擁有碩士（含）以上學歷的比例是否高於
50\% 進行檢驗。

\hypertarget{ux5340ux9593ux4f30ux8a08ux4fe1ux8cf4ux5340ux9593}{%
\subsubsection{區間估計（信賴區間）}\label{ux5340ux9593ux4f30ux8a08ux4fe1ux8cf4ux5340ux9593}}

\begin{itemize}
\tightlist
\item
  Wald 95\% 信賴區間：{[} 0.5021883,0.7978117 {]}
\item
  Score 95\% 信賴區間：{[} 0.5645095,0.709204 {]}
\item
  由於這兩個信賴區間的下限均高於 50\%（特別是 Score CI
  下限為0.5645），這顯示工程師擁有碩士學歷的比例很可能高於 50\%。
\end{itemize}

\hypertarget{ux5047ux8a2dux6aa2ux5b9aux7d50ux679c}{%
\subsubsection{假設檢定結果}\label{ux5047ux8a2dux6aa2ux5b9aux7d50ux679c}}

\begin{itemize}
\tightlist
\item
  Wald Test: \[檢定統計量t_w = 2.784573 > 1.645，拒絕H_0\]
\item
  Score Test: \[檢定統計量t_s = 2.675648 > 1.645，拒絕H_0\]
\item
  Small Sample Exact Test:
  \[p-value = 0.006029371（小於顯著水準 \alpha=0.05 )，拒絕H_0\]
  \[Mid p-value =  0.004171611（更小），進一步支持拒絕H_0\]
\end{itemize}

\hypertarget{ux7d50ux8ad6}{%
\subsubsection{📌 結論}\label{ux7d50ux8ad6}}

\begin{itemize}
\tightlist
\item
  由於 Wald Test、Score Test 和 Small Sample Exact Test 皆拒絕虛無假設
  \(H_0\)，並且 信賴區間的下限高於
  50\%，我們有足夠證據證明此次調查公司工程師的碩士學歷比例顯著高於
  50\%。
\item
  表示碩士（含）以上學歷在該公司內部可能是較為普遍的學歷背景，反映出科技產業對高等教育的重視程度。
\item
  所以我現在在念碩士。
\end{itemize}

\end{document}
